#spring.application.name=management
## H2 Database config
#spring.datasource.url=jdbc:h2:mem:studentdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## JPA config
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#
## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


## SQLite config
#spring.datasource.url=jdbc:sqlite:studentdb.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#
## JPA config
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


# MySQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/student_management
spring.datasource.username=root
spring.datasource.password=Marathon99$

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true